services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U adex" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all
    ports:
      - "5432:5432"
